/** Compare registered game placement with a contact/release timing proposal. No runtime edits. */
import{readFileSync,writeFileSync}from'node:fs';import{join}from'node:path';import{fileURLToPath}from'node:url';import{Pixels}from'../../source/pixels.ts';import{loadIndexed,clone,enlarged,indexedGif,homography}from'../../source/study-tools.ts';
const h=fileURLToPath(new URL('.',import.meta.url)),pal=JSON.parse(readFileSync(join(h,'../clock-r12/palette.json'),'utf8'));writeFileSync(join(h,'palette.json'),JSON.stringify(pal,null,2)+'\n');
const load=(p:string)=>loadIndexed(join(h,p),pal),bg=load('../clock-r12/export/background-clean.png'),front=load('../workshop-r9/export/workshop-front.png'),lamp=load('../workshop-r9/export/lamp-00.png'),hero=Array.from({length:4},(_,i)=>load('../holmes-r11/export/reach-'+i+'.png')),clock=Array.from({length:8},(_,i)=>load('../clock-r12/export/clock-'+String(i).padStart(2,'0')+'.png'));
const projection=JSON.parse(readFileSync(join(h,'../clock-r12/projection.json'),'utf8'));
const contactPoints=projection.poses.map((p:any)=>{const f=p.faces.find((f:any)=>f.kind==='front');return homography(f.uv,f.vertices.map((v:number[])=>v.slice(0,2)))(16,67)});
const current=Array.from({length:14},(_,i)=>({tick:i*8,heroCel:i<4?i:i<12?3:0,caseCel:i<4?0:Math.min(7,i-4)}));
const proposed=[
 [0,0,0,'Set hero position and face east'],[8,1,0,'Raise hand'],[16,2,0,'Make contact'],[24,2,0,'Brief contact hold; stop pendulum and swap to case cel 0'],[32,2,1,'Begin case movement; hand remains at contact for the first 10 degrees'],[40,3,2,'Release; hand withdraws as case reaches 22 degrees'],[48,1,3,'Return arm'],[56,0,4,'Return to standing'],[64,0,5,'Case continues'],[72,0,6,'Case continues'],[80,0,7,'Case reaches final angle'],[104,0,7,'End settle hold']
].map(([tick,heroCel,caseCel,note])=>({tick,heroCel,caseCel,note}));
const data={status:'Art timing proposal for engineer review, not runtime integration',ticksPerSecond:60,heroAnchor:[36,113],currentHeroPosition:[214,160],proposedHeroPosition:[223,165],clockPosition:[292,150],clockAnchor:[60,150],contact:{heroCel:2,handInCel:[67,29],currentWorld:[245,76],proposedWorld:[254,81],closedCaseUV:[16,67],projectedCasePoints:contactPoints,firstMovementDistance:Math.hypot(contactPoints[1]![0]-254,contactPoints[1]![1]-81),note:'Joint annotation approximates hand center. At the first 10° pose the surface moves about 2.2 native pixels; release after this, rather than holding the old hand pose throughout the swing.'},current,proposed,additionalCelsRequired:false,choreography:'Touch/trigger, initial push, then release and let the case swing. Continuous hand tracking through all 84 degrees would require new full-body poses; this proposal does not claim that.'};
writeFileSync(join(h,'timing.json'),JSON.stringify(data,null,2)+'\n');
function room(hc:number,cc:number,pos:number[],markers=false){const p=clone(bg);p.paste(lamp,203,80);p.paste(hero[hc]!,pos[0]!-36,pos[1]!-113);p.paste(clock[cc]!,232,0);p.paste(front,0,0);if(markers){const hand=[[43,41],[59,32],[67,29],[62,29]][hc]!,x=pos[0]!-36+hand[0]!,y=pos[1]!-113+hand[1]!;p.line(x-2,y,x+2,y,54);p.line(x,y-2,x,y+2,54);const q=contactPoints[cc]!;p.oval(q[0],q[1],1,1,61)}return p}
enlarged(join(h,'review/current-contact.png'),room(2,0,data.currentHeroPosition,true),pal,3);enlarged(join(h,'review/proposed-contact.png'),room(2,0,data.proposedHeroPosition,true),pal,3);
const frames=Array.from({length:18},(_,i)=>{const a=current.filter(s=>s.tick<=i*8).at(-1)!,b=proposed.filter(s=>Number(s.tick)<=i*8).at(-1)!,p=new Pixels(640,212,18);p.paste(room(a.heroCel,a.caseCel,data.currentHeroPosition),0,0);p.paste(room(Number(b.heroCel),Number(b.caseCel),data.proposedHeroPosition),320,0);p.text('CURRENT PLACEMENT / SEQUENCE',5,202,62);p.text('PROPOSED CONTACT / RELEASE',325,202,62);return p});
indexedGif(join(h,'review/comparison.gif'),frames,pal,2,13);
console.log({currentContact:[245,76],proposedContact:[254,81],firstCaseMotion:data.contact.firstMovementDistance,additionalCels:0});
