/** Victorian framed portraits: fixed face, paired facings, independent facial cels. */
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{Pixels}from'../../source/pixels.ts';import{loadIndexed,enlarged,indexedGif}from'../../source/study-tools.ts';import{pixeloramaProject}from'../../source/pixelorama-project.ts';
const h='art/studies/portraits-r21/',pal:string[]=JSON.parse(readFileSync(h+'palette.json','utf8'));
const specs=[{name:'watson',view:210,eyes:[[29,28,8,4],[39,28,5,4]],mouth:[37,41,7,4],lip:[38,42,5]},{name:'hudson',view:211,eyes:[[31,28,7,5],[40,28,5,5]],mouth:[35,39,9,5],lip:[36,40,6]},{name:'toby',view:212,eyes:[[29,30,8,5],[39,29,5,4]],mouth:[33,41,10,5],lip:[35,42,6]}];
const inside=(x:number,y:number)=>((x-27.5)/22.5)**2+((y-31.5)/25.5)**2<=1;
const frame=new Pixels(56,64),back=new Pixels(56,64);
// Turned brass oval: recessed inner lip, raised bead course, engraved outer edge.
for(let y=0;y<64;y++)for(let x=0;x<56;x++){const q=Math.sqrt(((x-27.5)/26.5)**2+((y-31.5)/30.5)**2),light=-(x-27.5)/26.5-(y-31.5)/30.5;if(inside(x,y)){back.dot(x,y,x<27?18:4);continue}if(q>1.03)continue;const c=q>1?2:q>.96?(light>0?39:15):q>.9?(light>.5?61:light>-.5?48:29):q>.87?(light>.3?55:39):q>.83?(light>.3?48:23):2;frame.dot(x,y,c)}
for(let i=0;i<48;i++){const a=i*Math.PI*2/48,x=27.5+24.7*Math.cos(a),y=31.5+28.5*Math.sin(a);frame.dot(x,y,(-Math.cos(a)-Math.sin(a))>0?61:44)}
for(const y of [2,61]){frame.oval(27.5,y,3,2,15);frame.line(25,y,30,y,48);frame.dot(27,y-1,61);frame.dot(28,y,55)}
// Four small acanthus-like curls stay within the oval's border, never over a face.
for(const[x,y,dx,dy]of [[9,10,1,1],[46,10,-1,1],[9,53,1,-1],[46,53,-1,-1]]){frame.line(x!,y!,x!+dx!*3,y!+dy!*3,48);frame.dot(x!+dx!,y!+dy!*2,61);frame.dot(x!+dx!*3,y!+dy!,39)}
function clip(p:Pixels){for(let y=0;y<64;y++)for(let x=0;x<56;x++)if(!inside(x,y)||frame.data[y*56+x]!>=0)p.data[y*56+x]=-1;return p}
function flip(p:Pixels){const out=new Pixels(56,64);for(let y=0;y<64;y++)for(let x=0;x<56;x++)out.dot(55-x,y,p.data[y*56+x]!);return out}
function crop(p:Pixels,r:number[]){const q=new Pixels(56,64);for(let y=r[1]!;y<r[1]!+r[3]!;y++)for(let x=r[0]!;x<r[0]!+r[2]!;x++)q.dot(x,y,p.data[y*56+x]!);return q}
function composite(ps:Pixels[]){const p=new Pixels(56,64);ps.forEach(q=>p.paste(q,0,0));return p}
const jobs:any[]=[],views:any[]=[],all:Record<string,Pixels[][]>={},checks:any[]=[];writeFileSync(h+'source/frame.png',frame.png(pal));writeFileSync(h+'source/backdrop.png',back.png(pal));
for(const s of specs){const face=loadIndexed(h+`source/${s.name}-face.png`,pal);
 // Small native accents restore purposeful features after reduction, not random texture.
 if(s.name==='watson'){face.dot(29,32,48);face.dot(28,31,48);face.line(33,37,35,36,39);face.dot(37,38,48);face.line(20,47,22,49,60);face.dot(32,29,63)}
 if(s.name==='hudson'){face.dot(30,33,48);face.dot(29,34,48);face.line(34,37,35,36,51);face.oval(32,54,2,1,48);face.dot(31,53,61);face.dot(32,54,2);face.dot(34,30,63)}
 if(s.name==='toby'){face.dot(27,36,48);face.dot(29,37,48);face.line(32,27,34,26,29);face.line(28,55,28,58,60);face.dot(32,31,63)}
 const mouths:Pixels[]=[],eyes:Pixels[]=[];for(let f=0;f<3;f++){const m=crop(face,s.mouth);if(f){const[x,y,w]=s.lip as[number,number,number];m.line(x,y,x+w-1,y,29);m.line(x+1,y+1,x+w-2,y+1,2);if(f===2){m.line(x+2,y+2,x+w-2,y+2,2);m.dot(x+2,y+1,58)}m.line(x+2,y+(f===1?2:3),x+w-3,y+(f===1?2:3),45)}mouths.push(m);const e=new Pixels(56,64);for(const r of s.eyes){e.paste(crop(face,r),0,0);if(f){const[x,y,w,hh]=r as[number,number,number,number];for(let xx=x;xx<x+w;xx++)e.rect(xx,y,1,f===1?2:hh,face.data[(y+hh)*56+xx]!);const yy=y+(f===1?1:2);e.line(x+1,yy,x+w-2,yy,39);if(f===2)e.dot(x+w-1,yy-1,39)}}eyes.push(e)}
 const rawFace=face,facings=[{name:'right',face:clip(composite([rawFace])),mouths:mouths.map(p=>clip(p)),eyes:eyes.map(p=>clip(p))},{name:'left',face:clip(flip(rawFace)),mouths:mouths.map(p=>clip(flip(p))),eyes:eyes.map(p=>clip(flip(p)))}];const loops:Pixels[][]=[];
 for(const[f,d]of facings.map((d,f)=>[f,d]as const)){const bust=composite([back,d.face,frame]);loops.push([bust],d.mouths,d.eyes);const combos=[[0,0],[1,0],[2,0],[0,1],[0,2],[1,1],[2,2]],layers=combos.map(([m,e])=>[back,d.face,frame,d.mouths[m!]!,d.eyes[e!]!]),key=s.name+'-'+d.name;writeFileSync(h+`source/${key}.pxo`,pixeloramaProject(pal,['Velvet backing','Fixed face','Victorian brass frame','Mouth overlay','Eye overlay'],layers,[{name:'mouth',from:1,to:3},{name:'blink',from:4,to:5}],{fps:8,layers:[{locked:true,linkAll:true},{locked:true,linkAll:true},{locked:true,linkAll:true},{},{}],userData:'56x64 [0,0]. Right loops0/1/2, left loops3/4/5. Fixed frame lighting; reflected face/overlays. No per-frame identity changes.'}));layers.forEach((ps,i)=>writeFileSync(h+`review/${key}-native-${i+1}.png`,composite(ps).png(pal)));jobs.push({name:key,expected:layers.map((_,i)=>`review/${key}-native-${i+1}.png`)});const neutral=composite([bust,d.mouths[0]!,d.eyes[0]!]);assert.deepEqual(neutral.data,bust.data);for(const p of [...d.mouths,...d.eyes])for(let i=0;i<p.data.length;i++)if(p.data[i]!>=0)assert.equal(frame.data[i],-1,'Overlay changed frame');enlarged(h+`review/${key}.png`,bust,pal,5);checks.push({name:key,neutralReconstructsBust:true,frameNeverChanges:true,bustSha256:createHash('sha256').update(bust.png(pal)).digest('hex')});}
 // Reflections affect only the face and facial cels. Brass highlights keep one light source.
 assert.deepEqual(facings[1]!.face.data,clip(flip(facings[0]!.face)).data);loops.forEach((fs,l)=>fs.forEach((p,c)=>writeFileSync(h+`export/${s.name}-${l}-${c}.png`,p.png(pal))));all[s.name]=loops;views.push({number:s.view,loops:loops.map((fs,l)=>({cels:fs.map((_,c)=>({png:`export/${s.name}-${l}-${c}.png`,anchor:[0,0]}))}))});
}
const sheet=new Pixels(186,150,18),animated:Pixels[]=[];specs.forEach((s,i)=>{sheet.paste(all[s.name]![0]![0]!,i*62,0);sheet.paste(all[s.name]![3]![0]!,i*62,79);sheet.text(s.name.toUpperCase(),i*62+3,68,62)});enlarged(h+'review/facings.png',sheet,pal,4);
for(let t=0;t<32;t++){const p=new Pixels(186,150,18);specs.forEach((s,k)=>{const m=[0,1,0,2,1,0,1,2][t%8]!,q=(t+k*7)%32,e=q===22||q===24?1:q===23?2:0;for(const f of [0,3]){p.paste(all[s.name]![f]![0]!,k*62,f===0?0:79);p.paste(all[s.name]![f+1]![m]!,k*62,f===0?0:79);p.paste(all[s.name]![f+2]![e]!,k*62,f===0?0:79)}p.text(s.name.toUpperCase(),k*62+3,68,62)});animated.push(p)}indexedGif(h+'review/facings.gif',animated,pal,4,13);
writeFileSync(h+'art.json',JSON.stringify({version:1,maxColours:64,palette:'palette.json',pictures:[],views},null,2)+'\n');writeFileSync(h+'native-jobs.json',JSON.stringify(jobs,null,2)+'\n');writeFileSync(h+'checks.json',JSON.stringify(checks,null,2)+'\n');writeFileSync(h+'guides/facing-contract.json',JSON.stringify({canvas:[56,64],anchor:[0,0],right:{bust:0,mouth:1,eyes:2},left:{bust:3,mouth:4,eyes:5},suggestedPlacement:{actorLeftHalf:{facing:'right',portrait:[8,8],textSide:'right'},actorRightHalf:{facing:'left',portrait:[256,8],textSide:'left'}},switchRule:'Choose on dialogue start from speaker screen x, not world x. Switch all three loops together and reset mouth/eyes to cel0. Retain that facing for the line.',engineStatus:'SCI supports six loops; current room compiler creates portrait parts with loops0/1/2 at a fixed location. Automatic facing/placement needs engine integration.'},null,2)+'\n');console.log({views:3,facings:2,cels:42,nativeProjects:6});
