/** Native X.Org bitmap proof. Preserve BBX offsets and DWIDTH; no rasterizing or resizing. */
import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{Pixels}from'../../source/pixels.ts';import{clone}from'../../source/study-tools.ts';
function enlarged(path:string,p:Pixels,palette:string[],scale:number){const q=new Pixels(p.width*scale,p.height*scale);for(let y=0;y<p.height;y++)for(let x=0;x<p.width;x++)q.rect(x*scale,y*scale,scale,scale,p.data[y*p.width+x]!);writeFileSync(path,q.png(palette))}
const h='art/studies/typography-r29/',pal:string[]=JSON.parse(readFileSync('art/palette.json','utf8'));
type Glyph={code:number,w:number,h:number,x:number,y:number,advance:number,rows:string[]};type Font={ascent:number,descent:number,glyphs:Map<number,Glyph>};
const fonts:Record<string,Font>={},metrics:any[]=[];
for(const family of ['ncen','tim'])for(const size of ['10','12'])for(const style of ['R','B','I','BI']){const name=family+style+size,s=readFileSync(h+`source/upstream/${name}.bdf`,'utf8'),f:Font={ascent:+s.match(/^FONT_ASCENT (\d+)/m)![1]!,descent:+s.match(/^FONT_DESCENT (\d+)/m)![1]!,glyphs:new Map()};for(const block of s.split('STARTCHAR ').slice(1)){const code=+block.match(/^ENCODING (-?\d+)/m)![1]!;if(code<32||code>126)continue;const[w,hh,x,y]=block.match(/^BBX (.+)/m)![1]!.split(' ').map(Number),advance=+block.match(/^DWIDTH (\d+)/m)![1]!,rows=block.split('BITMAP\n')[1]!.split('\nENDCHAR')[0]!.trim().split('\n');f.glyphs.set(code,{code,w:w!,h:hh!,x:x!,y:y!,advance,rows});}assert.equal(f.glyphs.size,95);fonts[name]=f;metrics.push({name,sha256:createHash('sha256').update(s).digest('hex'),ascent:f.ascent,descent:f.descent,minBearing:Math.min(...[...f.glyphs.values()].map(g=>g.x)),maxWidth:Math.max(...[...f.glyphs.values()].map(g=>g.w)),maxAdvance:Math.max(...[...f.glyphs.values()].map(g=>g.advance))})}
function draw(p:Pixels,key:string,s:string,x:number,baseline:number,c=2){for(const ch of s){const g=fonts[key]!.glyphs.get(ch.charCodeAt(0))!;assert.ok(g);for(let y=0;y<g.h;y++){const bits=BigInt('0x'+g.rows[y]!);const padded=g.rows[y]!.length*4;for(let xx=0;xx<g.w;xx++)if(bits>>BigInt(padded-1-xx)&1n)p.dot(x+g.x+xx,baseline-g.y-g.h+y,c)}x+=g.advance;}return x}
function label(p:Pixels,s:string,x:number,y:number){p.text(s,x,y,29)}
const proof=new Pixels(320,386,62),guided=clone(proof);for(const p of [proof,guided]){label(p,'NATIVE BITMAP FONTS / UNALTERED PIXELS',10,8);let top=26;for(const family of ['ncen','tim'])for(const size of ['10','12']){label(p,(family==='ncen'?'NEW CENTURY SCHOOLBOOK':'TIMES')+' / '+size+'PX',10,top);['R','B','I','BI'].forEach((style,k)=>{const baseline=top+27+k*16;if(p===guided)p.line(9,baseline,310,baseline,58);draw(p,family+style+size,'The boy is frightened. Hear him out.',10,baseline)});top+=90}}enlarged(h+'review/comparison.png',proof,pal,3);enlarged(h+'review/baselines.png',guided,pal,3);
// Give the recommended 12px family a roomier, realistic dialogue proof.
const dialogue=new Pixels(320,200,18);dialogue.rect(8,14,304,172,29);dialogue.rect(11,17,298,166,62);let y=34;for(const[style,title]of [['R','Regular'],['B','Bold'],['I','Italic'],['BI','Bold italic']]){draw(dialogue,'ncenB12',title!,22,y);draw(dialogue,'ncen'+style+'12','The boy is frightened. Hear him out.',22,y+16);y+=37}enlarged(h+'review/schoolbook.png',dialogue,pal,3);
writeFileSync(h+'guides/source-metrics.json',JSON.stringify(metrics,null,2)+'\n');writeFileSync(h+'guides/validation.json',JSON.stringify({sourcePackage:'font-adobe-75dpi-1.0.4',families:2,sizes:[10,12],facesPerSize:4,glyphs:16*95,pixelResampling:false,preserved:['BBX offsets','DWIDTH advances','baseline'],status:'comparison only; no runtime conversion'},null,2)+'\n');console.log('16 upstream bitmap faces; 1520 ASCII glyphs; original metrics preserved.');
