/** Painted UI masters -> indexed sprites and editable native projects. */
import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{decodePng}from'sci2-ts/png';import{Pixels}from'../../source/pixels.ts';import{clone,loadIndexed,enlarged}from'../../source/study-tools.ts';import{pixeloramaProject}from'../../source/pixelorama-project.ts';
const h='art/studies/interface-r28/',pal:string[]=JSON.parse(readFileSync('art/studies/interface-r27/palette.json','utf8')),base=pal.slice(0,63).concat('#ffffff'),rgb=pal.map(c=>[1,3,5].map(i=>parseInt(c.slice(i,i+2),16))),names=['walk','look','use','talk','inventory','menu'],jobs:any[]=[];
writeFileSync(h+'palette.json',JSON.stringify(pal,null,2)+'\n');
function nearest(r:number,g:number,b:number){let best=Infinity,k=0;rgb.forEach((v,i)=>{if(b>g*1.3&&r>g*1.2&&b>r*.6&&![63,64,65,66].includes(i))return;const d=2*(v[0]!-r)**2+4*(v[1]!-g)**2+(v[2]!-b)**2;if(d<best){best=d;k=i}});return k}
function put(name:string,p:Pixels){writeFileSync(h+`export/${name}.png`,p.png(pal))}
function project(name:string,layers:string[],frames:Pixels[][],expected:string[]){writeFileSync(h+`source/${name}.pxo`,pixeloramaProject(pal,layers,frames));jobs.push({name,expected})}
function crop(p:Pixels,x:number,y:number,w:number,hh:number){const q=new Pixels(w,hh);for(let yy=0;yy<hh;yy++)for(let xx=0;xx<w;xx++)q.dot(xx,yy,p.data[(y+yy)*p.width+x+xx]!);return q}
function resize(p:Pixels,w:number,hh:number){const q=new Pixels(w,hh);for(let y=0;y<hh;y++)for(let x=0;x<w;x++)q.dot(x,y,p.data[Math.floor((y+.5)*p.height/hh)*p.width+Math.floor((x+.5)*p.width/w)]!);return q}
const raw=decodePng(readFileSync(h+'generated/icons.png')),cw=raw.width/3,ch=raw.height/2,crops:number[][]=[];
function object(n:number,size:number){const ox=n%3*cw,oy=Math.floor(n/3)*ch,removed=new Uint8Array(cw*ch),todo:number[]=[];for(let x=0;x<cw;x++)todo.push(x,(ch-1)*cw+x);for(let y=0;y<ch;y++)todo.push(y*cw,y*cw+cw-1);
 while(todo.length){const i=todo.pop()!;if(removed[i])continue;const x=i%cw,y=Math.floor(i/cw),at=((oy+y)*raw.width+ox+x)*4,r=raw.data[at]!,g=raw.data[at+1]!,b=raw.data[at+2]!;if(!(b>r+2&&r>g+3&&g<100))continue;removed[i]=1;if(x)todo.push(i-1);if(x<cw-1)todo.push(i+1);if(y)todo.push(i-cw);if(y<ch-1)todo.push(i+cw);}
 let l=cw,t=ch,r=0,b=0;for(let y=0;y<ch;y++)for(let x=0;x<cw;x++)if(!removed[y*cw+x]){l=Math.min(l,x);t=Math.min(t,y);r=Math.max(r,x);b=Math.max(b,y)}
 if(size===32)crops.push([ox+l,oy+t,r-l+1,b-t+1]);const factor=(size-4)/Math.max(r-l+1,b-t+1),w=Math.max(1,Math.round((r-l+1)*factor)),hh=Math.max(1,Math.round((b-t+1)*factor)),p=new Pixels(size,size),px=Math.floor((size-w)/2),py=Math.floor((size-hh)/2);
 for(let y=0;y<hh;y++)for(let x=0;x<w;x++){const sx=Math.floor(l+(x+.5)*(r-l+1)/w),sy=Math.floor(t+(y+.5)*(b-t+1)/hh),at=((oy+sy)*raw.width+ox+sx)*4;if(!removed[sy*cw+sx])p.dot(px+x,py+y,nearest(raw.data[at]!,raw.data[at+1]!,raw.data[at+2]!))}return p}
const icons32=names.map((_,i)=>object(i,32)),icons24=names.map((_,i)=>object(i,24));
const cr=decodePng(readFileSync(h+'generated/case.png'));let l=cr.width,t=cr.height,r=0,b=0;for(let y=0;y<cr.height;y++)for(let x=0;x<cr.width;x++)if(cr.data[(y*cr.width+x)*4+3]!>220){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}
const cse=new Pixels(256,144);for(let y=0;y<144;y++)for(let x=0;x<256;x++){const sx=Math.floor(l+(x+.5)*(r-l+1)/256),sy=Math.floor(t+(y+.5)*(b-t+1)/144),at=(sy*cr.width+sx)*4;if(cr.data[at+3]!>180)cse.dot(x,y,nearest(cr.data[at]!,cr.data[at+1]!,cr.data[at+2]!))}put('case-empty',cse);project('case-empty',['Walnut and velvet'],[[cse]],['export/case-empty.png']);
const fonts=Object.fromEntries(['regular','bold'].map(n=>[n,JSON.parse(readFileSync(`art/studies/typography-r26/source/${n}.json`,'utf8'))]));function text(p:Pixels,s:string,x:number,y:number,face='regular',ink=62){for(const ch of s){const g=fonts[face].find((g:any)=>g.code===ch.charCodeAt(0));let right=-1;g.rows.forEach((row:string,yy:number)=>[...row].forEach((c,xx)=>{if(c==='#'){p.dot(x+xx,y+yy,ink);right=Math.max(right,xx)}}));x+=ch===' '?3:right+2}return x}
const lining=resize(crop(cse,16,28,48,38),32,32),bars32=[0,1].map(s=>icons32.map(obj=>{const p=clone(lining);p.paste(obj,0,s?-1:0);if(s)p.line(8,30,23,30,61);return p})),lining24=resize(lining,24,24),bars24=[0,1].map(s=>icons24.map(obj=>{const p=clone(lining24);p.paste(obj,0,s?-1:0);if(s)p.line(6,22,17,22,61);return p}));
for(const[size,icons,bars]of [[32,icons32,bars32],[24,icons24,bars24]]as const){icons.forEach((p,i)=>put(`object-${names[i]}-${size}`,p));project(`objects-${size}`,['Transparent object'],icons.map(p=>[p]),names.map(n=>`export/object-${n}-${size}.png`));bars.forEach((ps,loop)=>{ps.forEach((p,i)=>put(`icons-${size}-${loop}-${i}`,p));project(`icons-${size}-${loop}`,['Velvet','Object and selection'],ps.map((p,i)=>{const fore=clone(icons[i]!);if(loop){fore.data.fill(-1);fore.paste(icons[i]!,0,-1);fore.line(size===32?8:6,size-2,size===32?23:17, size-2,61)}return[size===32?lining:lining24,fore]}),ps.map((_,i)=>`export/icons-${size}-${loop}-${i}.png`))});}
const toolbar=new Pixels(320,48,64);toolbar.paste(resize(crop(cse,0,0,256,11),320,8),0,0);toolbar.paste(resize(crop(cse,0,130,256,14),320,8),0,40);toolbar.paste(resize(crop(cse,0,16,10,113),8,32),0,8);toolbar.paste(resize(crop(cse,246,16,10,113),8,32),312,8);
for(let i=0;i<7;i++){toolbar.paste(lining,16+i*42,8);if(i<6)toolbar.paste(resize(crop(cse,66,27,5,36),5,32),51+i*42,8)}put('toolbar-empty',toolbar);const filled=clone(toolbar),positions=[16,58,100,142,226,268];names.forEach((_,i)=>filled.paste(bars32[+(i===0)]![i]!,positions[i]!,8));put('toolbar-composite',filled);
const inventory=clone(cse);inventory.paste(icons32[1]!,20,35);text(inventory,'CASE',115,11,'bold',29);text(inventory,'Magnifying lens',13,123);put('case-composite',inventory);
for(const[name,p]of [['toolbar-empty',toolbar],['toolbar-composite',filled],['case-composite',inventory]]as const)project(name,[name],[[p]],[`export/${name}.png`]);
function original(path:string){const p=loadIndexed(path,base);for(let i=0;i<p.data.length;i++)if(p.data[i]===63)p.data[i]=67;return p}const room=original('art/studies/baker-street-r13/export/background.png');const ri=clone(room);ri.paste(inventory,32,30);enlarged(h+'review/inventory.png',ri,pal,3);const rb=clone(room);rb.paste(filled,0,0);enlarged(h+'review/toolbar.png',rb,pal,3);
const board=new Pixels(320,194,4);text(board,'Painted symbols / 32 px',12,8,'bold');icons32.forEach((p,i)=>board.paste(p,12+i*50,29));names.forEach((n,i)=>text(board,n==='inventory'?'case':n,12+i*50,66));text(board,'Current engine size / 24 px',12,87,'bold');icons24.forEach((p,i)=>board.paste(p,16+i*50,108));text(board,'Talk: ivory card, ink dots, folded corner',12,147);text(board,'Material detail without individual frames',12,166);enlarged(h+'review/icons.png',board,pal,3);
function manifest(size:number){return{version:1,maxColours:68,palette:'palette.json',pictures:[],views:[{number:266,loops:[0,1].map(loop=>({cels:names.map((_,i)=>({png:`export/icons-${size}-${loop}-${i}.png`,anchor:[0,0]}))}))},{number:250,loops:[{cels:[{png:`export/object-look-${size}.png`,anchor:[0,0]}]}]}]}}writeFileSync(h+'art.json',JSON.stringify(manifest(32),null,2)+'\n');writeFileSync(h+'art-24.json',JSON.stringify(manifest(24),null,2)+'\n');writeFileSync(h+'native-jobs.json',JSON.stringify(jobs,null,2)+'\n');writeFileSync(h+'guides/handoff.json',JSON.stringify({status:'review; 32px needs engine contract change',icons:{preferred:32,compatibility:24,order:names,x:positions,y:8,activeItem:[184,8]},case:{size:[256,144],origin:[32,30],grid:[4,2],slotOrigins:[[13,28],[73,28],[133,28],[193,28],[13,75],[73,75],[133,75],[193,75]],itemInset:[7,7]},palette:'r27 additive 68-colour proposal, original colours preserved',sourceCrops:crops,sourceCaseBounds:[l,t,r-l+1,b-t+1],notes:['Engine ICON_SIZE is 24. Preferred 32px icons require coordinated hitbox, gap, item icon and toolbar layout changes.','24px manifest is provided for size comparison, not a full production replacement.','Item cursor not redesigned; retain the separately reviewed 16px cursor loop when integrating view 250.','Empty case and toolbar skins are separate from objects; approved portrait and font assets remain unchanged.']},null,2)+'\n');assert.deepEqual(pal.slice(0,63).concat(pal[67]!),base);console.log({icons:6,sizes:[32,24],nativeProjects:jobs.length,case:[256,144]});
