import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {Pixels} from '../../source/pixels.ts';
import {loadIndexed,enlarged,clone} from '../../source/study-tools.ts';
import {pixeloramaProject} from '../../source/pixelorama-project.ts';
const h='art/studies/typography-r26/',pal:string[]=JSON.parse(readFileSync('art/palette.json','utf8')),names=['regular','bold','italic','bold-italic'];
const faces:Record<string,Pixels[]>={},metrics:Record<string,number[]>={},fonts:any[]=[],jobs:any[]=[];
writeFileSync(h+'palette.json',JSON.stringify(pal,null,2)+'\n');
for(const[name,k]of names.map((n,i)=>[n,i]as const)){const glyphs=JSON.parse(readFileSync(h+`source/${name}.json`,'utf8')) as {code:number,rows:string[]}[],sheet=new Pixels(152,60);faces[name]=[];metrics[name]=[];for(const{code,rows}of glyphs){assert.equal(rows.length,12);const g=new Pixels(8,12);let right=-1;rows.forEach((row,y)=>{assert.equal(row.length,8);[...row].forEach((c,x)=>{if(c==='#'){g.dot(x,y,62);right=Math.max(right,x)}})});assert.ok(code===32||right>=0,`missing ${name} ${code}`);faces[name]![code]=g;metrics[name]![code]=code===32?3:right+2;sheet.paste(g,(code-32)%19*8,Math.floor((code-32)/19)*12)}
 writeFileSync(h+`export/${name}.png`,sheet.png(pal));writeFileSync(h+`source/${name}.pxo`,pixeloramaProject(pal,[name+' 8x12 ASCII'],[[sheet]]));jobs.push({name,expected:[`export/${name}.png`]});fonts.push({number:k+1,png:`export/${name}.png`,cell:[8,12],first:32,spacing:1,space:3,lineHeight:12});}
function text(p:Pixels,s:string,x:number,y:number,face='regular',colour=2){for(const ch of s){const code=ch.charCodeAt(0),g=faces[face]![code];assert.ok(g,`unsupported ${ch}`);for(let yy=0;yy<12;yy++)for(let xx=0;xx<8;xx++)if(g.data[yy*8+xx]!>=0)p.dot(x+xx,y+yy,colour);x+=metrics[face]![code]!}return x}
function runs(p:Pixels,rs:[string,string][],x:number,y:number,w:number){const start=x;for(const[face,s]of rs)for(const token of s.match(/\S+|\s+/g)??[]){const wide=[...token].reduce((n,c)=>n+metrics[face]![c.charCodeAt(0)]!,0);if(x+wide>start+w&&!/^\s+$/.test(token)){x=start;y+=12;}if(x===start&&/^\s+$/.test(token))continue;x=text(p,token,x,y,face)}return y+12}
const sheet=new Pixels(320,220,62);text(sheet,'Baker Street / A printer\'s specimen',12,9,'bold');for(let i=0;i<4;i++){const name=names[i]!;text(sheet,['Regular','Bold','Italic','Bold italic'][i]!,12,31+i*40,'bold');text(sheet,'The boy is frightened. Hear him out, Holmes.',12,45+i*40,name);text(sheet,'Aa Bb Gg Mm Ww 0123456789 !? "quotes"',12,57+i*40,name)}text(sheet,'Four faces / 8 x 12 cells / shared baseline',12,202,'italic');enlarged(h+'review/specimen.png',sheet,pal,3);
const frame=Array.from({length:8},(_,i)=>loadIndexed(`art/studies/interface-r25/export/box-frame-0-${i}.png`,pal));
function panel(w:number,hh:number){const p=new Pixels(w,hh,62);for(let x=14;x<w;x+=14){p.paste(frame[4]!,x,0);p.paste(frame[5]!,x,hh-14)}for(let y=14;y<hh;y+=14){p.paste(frame[6]!,0,y);p.paste(frame[7]!,w-14,y)}[[0,0],[w-14,0],[0,hh-14],[w-14,hh-14]].forEach(([x,y],i)=>p.paste(frame[i]!,x!,y!));return p}
const room=loadIndexed('art/studies/baker-street-r13/export/background.png',pal),surround=loadIndexed('art/studies/portraits-r22/export/surround.png',pal),portrait=loadIndexed('art/studies/portraits-r23/export/watson-0-0.png',pal);
const mixed:[string,string][]=[['bold','Watson: '],['regular','The boy is '],['italic','frightened'],['regular',' half out of his wits. '],['bold-italic','Hear him out'],['regular',', Holmes.']];
for(const face of ['mixed',...names]){const scene=clone(room),box=panel(228,80);runs(box,face==='mixed'?mixed:[[face,'Watson: The boy is frightened half out of his wits. Hear him out, Holmes.']],18,18,192);scene.paste(surround,5,5);scene.paste(portrait,13,23);scene.paste(box,86,13);const narration=panel(304,60);runs(narration,[['regular',"I am in my armchair, with yesterday's "],['italic','Standard'],['regular',', read twice over.']],18,18,268);scene.paste(narration,8,132);writeFileSync(h+`review/dialogue-${face}-native.png`,scene.png(pal));enlarged(h+`review/dialogue-${face}.png`,scene,pal,3)}
const grid=new Pixels(320,228,62);names.forEach((name,k)=>{text(grid,['REGULAR','BOLD','ITALIC','BOLD ITALIC'][k]!,8,k*57+2,'bold');for(let code=32;code<=126;code++)text(grid,String.fromCharCode(code),8+(code-32)%32*9,k*57+16+Math.floor((code-32)/32)*12,name)});enlarged(h+'review/glyphs.png',grid,pal,3);
writeFileSync(h+'art.json',JSON.stringify({version:1,maxColours:64,palette:'palette.json',pictures:[],views:[],fonts},null,2)+'\n');writeFileSync(h+'native-jobs.json',JSON.stringify(jobs,null,2)+'\n');writeFileSync(h+'guides/metrics.json',JSON.stringify({cell:[8,12],baseline:9,lineHeight:12,first:32,last:126,spacing:1,space:3,faces:metrics},null,2)+'\n');writeFileSync(h+'guides/sample-runs.json',JSON.stringify({status:'proposed handoff; not runtime syntax',lineId:'100-020',runs:mixed.map(([style,text])=>({style,text})),fonts:Object.fromEntries(names.map((n,i)=>[n,i+1])),requirements:['Measure, wrap and draw the same run stream.','Preserve style across wrapped lines; restore regular after each span.','Keep speaker names bold and print titles italic without emitting markup as text.','Map typographic punctuation before the ASCII bitmap boundary.']},null,2)+'\n');console.log('4 faces, 380 ASCII cells, 8x12, 12px line height');
