import{root,readFileSync,Pixels,read,save,json,review,gif,convert,mask,extract,clone,assert,project,layered,actor,holmes,watson,rgb,nearest,celView,crop,type Point}from'./common.ts';
export function passage(){
 const room=convert('stair'),guide=JSON.parse(readFileSync(root+'guides/stair.json','utf8'));
 const previous=JSON.parse(readFileSync('art/studies/stair-r40/guides/stair.json','utf8'));assert.deepEqual(guide.camera,previous.camera);assert.deepEqual(guide.walkable,previous.walkable);
 const defs=[{name:'stair-clock-back',priority:154,rects:[[0,27,59,127]]},{name:'stair-wall-return',priority:152,rects:[[59,0,18,154],[246,0,18,151],[59,0,205,6]]},{name:'stair-tools',priority:158,rects:[[264,122,56,36]]}];
 const layers=defs.map(d=>{const m=new Pixels(320,200);d.rects.forEach(([x,y,w,h])=>m.rect(x!,y!,w!,h!,0));const p=extract(room,m);save('guides/'+d.name+'-mask.png',m);project(d.name,[p]);return{name:d.name,p}});
 project('stair-background',[room]);layered('stair-edit-master',[{name:'Secret passage',p:room},...layers]);
 const origin:Point=[121,22],size:Point=[80,76],levels=[0,-.14,.08,-.26,-.06,.14],timeline=[0,0,1,0,2,0,0,4,1,3,4,0,2,2,0,0,1,4,0,5,2,0,0,4,1,0,2,0,4,0,0,0];
 const lamps=levels.map((level,cel)=>{const p=crop(room,...origin,...size);for(let y=0;y<size[1];y++)for(let x=0;x<size[0];x++){const xx=x+origin[0],yy=y+origin[1],i=y*size[0]+x,c=rgb[p.data[i]!]!,fall=Math.max(0,1-((xx-160)/34)**2-((yy-57)/34)**2)**2;const housing=xx>=155&&xx<=165&&yy>=44&&yy<=64;if(!housing&&c[0]!>35&&c[0]!>c[1]!*1.2)p.data[i]=nearest([c[0]!+85*level*fall,c[1]!+48*level*fall,c[2]!+12*level*fall]);}
 // Replace flame from the same clean dark glass each cel; no accumulation or doubled tips.
 p.rect(38,34,3,5,45);const lean=[0,0,1,0,-1,1][cel]!;p.dot(39+lean,35,50);p.dot(39,36,61);p.dot(39,37,cel===3?55:62);p.dot(38,38,55);p.dot(39,38,61);if(cel===5)p.dot(39,34,55);return p;});project('passage-lamp',lamps,8);
 // Small glimpse of the same working pendulum through the clock back.
 const peekOrigin:Point=[19,53],peekSize:Point=[13,30],peekOriginal=crop(room,...peekOrigin,...peekSize),peekFixed=clone(peekOriginal),bob=new Pixels(...peekSize);
 // Inside the rectangular inspection slot only; the rough planks remain pinned.
 for(let y=0;y<28;y++)for(let x=1;x<12;x++)peekFixed.dot(x,y,(x===1||x===11)?2:1);
 for(let y=16;y<=24;y++)for(let x=1;x<=11;x++)if(((x-6)/5)**2+((y-20)/4.5)**2<=1)bob.dot(x,y,peekOriginal.data[y*13+x]!);
 const peeks=Array.from({length:24},(_,i)=>{const p=clone(peekFixed),dx=Math.round(Math.sin(i/24*Math.PI*2)*2);p.line(6,0,6+dx,18,39);p.line(7,0,7+dx,18,48);p.paste(bob,dx,0);return p});project('passage-peek',peeks,12);
 const cast=clone(room);cast.paste(lamps[0]!,...origin);cast.paste(peeks[0]!,...peekOrigin);actor(cast,holmes,117,177);actor(cast,watson,230,181);review('stair-cast',cast);review('stair-empty',room);
 gif('passage',Array.from({length:96},(_,i)=>{const p=clone(room);p.paste(lamps[timeline[i%32]!]!,...origin);p.paste(peeks[Math.floor(i*.12*12)%24]!,...peekOrigin);return p}),2,12);
 gif('passage-lamp',timeline.map(i=>lamps[i]!),4,12);gif('passage-peek',peeks,7,8);
 const scales=new Pixels(960,432,18);guide.scaleChecks.forEach((g:any,i:number)=>{const p=clone(room);actor(p,holmes,...g.feet as Point);scales.paste(p,i%3*320,Math.floor(i/3)*216)});review('stair-scales',scales,1);
 const outline=clone(room);guide.walkable.forEach((p:Point,i:number)=>outline.line(...p,...guide.walkable[(i+1)%guide.walkable.length] as Point,61));review('stair-walkable',outline);
 const handoff={picture:103,perspective:guide.camera,walkable:guide.walkable,arrival:[90,174],hero:[117,177],watson:[230,181],hotspots:{stairs:[78,138,215,151],entranceDoor:[0,28,58,152],mechanism:[254,10,279,123],workApron:[286,34,313,121],tools:[270,120,319,156]},layers:defs,lamp:{view:283,origin,size,anchor:[0,0],priority:80,tickMs:120,timeline,loopMs:3840},peek:{view:287,origin:peekOrigin,size:peekSize,anchor:[0,0],priority:155,fps:12,frames:24,loopMs:2000},notes:['Keep r40 camera, walking strip, entrance and stair hotspots.','entranceDoor is now the back of the clock; update the description.','Mechanism/apron/tools rectangles are optional new interactions for the writer.','The 24-cel peek is a candidate new view 287; confirm ID availability. Draw after the clock-back layer.','Use the timeline for lamp view 283, not six equally spaced cels.','Background, occlusion and lamp must update together to prevent old furnishings reappearing.','No rug, table, umbrella stand or scarf remain. Cobwebs are kept off the route.']};json('guides/stair-handoff.json',handoff);
 // Same passage, dimmed with the pinned palette, plus editable native BDF lettering.
 const dark=clone(room);dark.data.forEach((v,i)=>dark.data[i]=nearest(rgb[v]!.map(c=>c*.42)));
 const lettering=new Pixels(320,200);drawCentered(lettering,'To be continued',95,'ncenR12',62);lettering.line(101,106,218,106,48);lettering.oval(160,106,2,1,61);drawCentered(lettering,'The Case of the Clerkenwell Clocks',124,'ncenR10',60);
 project('end-background',[dark]);project('end-lettering',[lettering]);const end=layered('end-card',[{name:'Same passage in shadow',p:dark},{name:'New Century lettering',p:lettering}]);review('end-card',end);
 return {pictures:[{number:103,layers:[{png:'export/stair-background-0.png',priority:-1000},...defs.map(d=>({png:`export/${d.name}-0.png`,priority:d.priority}))]},{number:105,layers:[{png:'export/end-background-0.png',priority:-1000},{png:'export/end-lettering-0.png',priority:0}]}],views:[celView(283,'passage-lamp',6),celView(287,'passage-peek',24)]};
}
function drawCentered(p:Pixels,text:string,baseline:number,font:string,c:number){const bdf=readFileSync('art/studies/typography-r29/source/upstream/'+font+'.bdf','utf8'),glyphs=new Map<number,{w:number;h:number;x:number;y:number;advance:number;rows:string[]}>();for(const block of bdf.split('STARTCHAR ').slice(1)){const code=+block.match(/^ENCODING (-?\d+)/m)![1]!,[w,h,x,y]=block.match(/^BBX (.+)/m)![1]!.split(' ').map(Number),advance=+block.match(/^DWIDTH (\d+)/m)![1]!;glyphs.set(code,{w:w!,h:h!,x:x!,y:y!,advance,rows:block.split('BITMAP\n')[1]!.split('\nENDCHAR')[0]!.trim().split('\n')});}let x=Math.round((320-[...text].reduce((n,ch)=>n+glyphs.get(ch.charCodeAt(0))!.advance,0))/2);for(const ch of text){const g=glyphs.get(ch.charCodeAt(0))!;for(let y=0;y<g.h;y++)for(let xx=0;xx<g.w;xx++)if(BigInt('0x'+g.rows[y]!)>>BigInt(g.rows[y]!.length*4-1-xx)&1n)p.dot(x+g.x+xx,baseline-g.y-g.h+y,c);x+=g.advance}}
