/** Reuse painted walnut/velvet, render original bitmap metrics, export states independently. */
import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{decodePng}from'sci2-ts/png';import{Pixels}from'../../source/pixels.ts';import{clone,loadIndexed,enlarged,indexedGif}from'../../source/study-tools.ts';import{pixeloramaProject}from'../../source/pixelorama-project.ts';
const h='art/studies/interface-r32/',pal:string[]=JSON.parse(readFileSync(h+'palette.json','utf8')),rgb=pal.map(c=>[1,3,5].map(i=>parseInt(c.slice(i,i+2),16))),jobs:any[]=[];
function save(n:string,p:Pixels){writeFileSync(h+`export/${n}.png`,p.png(pal))}
function project(n:string,frames:Pixels[],paths:string[]){writeFileSync(h+`source/${n}.pxo`,pixeloramaProject(pal,[n],frames.map(p=>[p])));jobs.push({name:n,expected:paths.map(p=>'export/'+p+'.png')})}
function crop(p:Pixels,x:number,y:number,w:number,hh:number){const q=new Pixels(w,hh);for(let yy=0;yy<hh;yy++)for(let xx=0;xx<w;xx++)q.dot(xx,yy,p.data[(y+yy)*p.width+x+xx]!);return q}
function resize(p:Pixels,w:number,hh:number){const q=new Pixels(w,hh);for(let y=0;y<hh;y++)for(let x=0;x<w;x++)q.dot(x,y,p.data[Math.floor((y+.5)*p.height/hh)*p.width+Math.floor((x+.5)*p.width/w)]!);return q}
const raw=decodePng(readFileSync(h+'generated/objects.png')),bounds:number[][]=[];
function object(cell:number,size:number){const ox=cell*raw.width/2,cw=raw.width/2;let l=cw,r=0,t=raw.height,b=0;for(let y=0;y<raw.height;y++)for(let x=0;x<cw;x++)if(raw.data[(y*raw.width+ox+x)*4+3]!>=220){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}
 if(size===32)bounds[cell]=[ox+l,t,r-l+1,b-t+1];const scale=(size-3)/Math.max(r-l+1,b-t+1),w=Math.round((r-l+1)*scale),hh=Math.round((b-t+1)*scale),p=new Pixels(size,size);
 for(let y=0;y<hh;y++)for(let x=0;x<w;x++){const sx=Math.floor(ox+l+(x+.5)*(r-l+1)/w),sy=Math.floor(t+(y+.5)*(b-t+1)/hh),a=(sy*raw.width+sx)*4;if(raw.data[a+3]!<220)continue;let best=Infinity,k=0;rgb.forEach((c,i)=>{const d=2*(c[0]!-raw.data[a]!)**2+4*(c[1]!-raw.data[a+1]!)**2+(c[2]!-raw.data[a+2]!)**2;if(d<best){best=d;k=i}});p.dot(Math.floor((size-w)/2)+x,Math.floor((size-hh)/2)+y,k)}return p}
const objs=new Map<string,Pixels>();for(const size of [32,24,16])for(const[cell,name]of [[0,'hourglass'],[1,'sound-on']]as const){const p=object(cell,size);save(`${name}-${size}`,p);objs.set(`${name}-${size}`,p)}
// Off removes the separate sound arcs, adds a restrained diagonal ivory mute stroke.
for(const size of [32,24,16]){const p=clone(objs.get(`sound-on-${size}`)!);p.rect(Math.round(size*.79),0,size,Math.round(size*.76),-1);p.line(Math.round(size*.24),Math.round(size*.76),Math.round(size*.75),Math.round(size*.23),4);p.line(Math.round(size*.24),Math.round(size*.76)-1,Math.round(size*.75),Math.round(size*.23)-1,62);save(`sound-off-${size}`,p);objs.set(`sound-off-${size}`,p)}
for(const size of [32,24,16]){const entries=[...objs.entries()].filter(([n])=>n.endsWith('-'+size));project('objects-'+size,entries.map(e=>e[1]),entries.map(e=>e[0]))}
const fonts=Object.fromEntries(['regular','bold','italic'].map(style=>[style,{metrics:JSON.parse(readFileSync(`art/studies/typography-r29/export/${style}.json`,'utf8')),atlas:loadIndexed(`art/studies/typography-r29/export/${style}.png`,JSON.parse(readFileSync('art/palette.json','utf8')))}]));
function text(p:Pixels,s:string,x:number,y:number,style='regular',ink=62){for(const ch of s){const f=fonts[style]!,g=f.metrics.glyphs[ch.charCodeAt(0)-32];assert.ok(g);const[sx,sy,w,hh]=g.rect;for(let yy=0;yy<hh;yy++)for(let xx=0;xx<w;xx++)if(f.atlas.data[(sy+yy)*f.atlas.width+sx+xx]!>=0)p.dot(x+g.bearingX+xx,y+g.top+yy,ink);x+=g.advance}return x}
const cse=loadIndexed('art/studies/interface-r28/export/case-empty.png',pal);
function skin(w:number,hh:number){const p=new Pixels(w,hh,64);const cloth=crop(cse,16,28,48,38);for(let i=0;i<cloth.data.length;i++)cloth.data[i]=cloth.data[i]===66?65:64;p.paste(cloth,w-57,hh-47);p.paste(resize(crop(cse,0,0,256,11),w,10),0,0);p.paste(resize(crop(cse,0,130,256,14),w,10),0,hh-10);p.paste(resize(crop(cse,0,16,10,113),9,hh-20),0,10);p.paste(resize(crop(cse,246,16,10,113),9,hh-20),w-9,10);return p}
const menu=skin(244,178);text(menu,'The casebook',85,10,'bold');menu.line(20,25,223,25,39);save('menu-empty',menu);project('menu-empty',[menu],['menu-empty']);
const states=['normal','hover','pressed','disabled'] as const;
const rows=states.map(state=>{const p=new Pixels(224,22);if(state==='hover'||state==='pressed'){p.rect(0,0,224,22,state==='pressed'?63:65);p.line(0,0,223,0,state==='pressed'?29:48);p.line(0,21,223,21,state==='pressed'?48:29);p.line(0,1,0,20,39);p.line(223,1,223,20,39)}save('row-'+state,p);return p});project('menu-rows',rows,states.map(s=>'row-'+s));
const bullets=states.map(state=>{const p=new Pixels(12,12);const dark=state==='disabled'?29:30,mid=state==='disabled'?40:48,light=state==='disabled'?41:61;p.poly([[6,1],[10,6],[6,10],[1,6]],dark);p.poly([[6,2],[9,6],[6,9],[2,6]],mid);p.line(6,2,2,6,light);p.dot(5,4,62);p.dot(6,6,dark);if(state==='hover'||state==='pressed')p.dot(6,6,62);save('bullet-'+state,p);return p});project('menu-bullets',bullets,states.map(s=>'bullet-'+s));
const labels=['Save the game','Restore a game','Start again','Text speed: normal','Speech: voice and text','Carry on'];
function row(i:number,state:typeof states[number]){const s=states.indexOf(state),p=clone(rows[s]!);p.paste(bullets[s]!,5,5);text(p,labels[i]!,25+(state==='pressed'?1:0),4+(state==='pressed'?1:0),'regular',state==='disabled'?51:state==='hover'?62:state==='pressed'?58:60);return p}
for(let i=0;i<6;i++)for(const state of states)save(`menu-item-${i}-${state}`,row(i,state));
const composites=states.slice(0,3).map(state=>{const p=clone(menu);labels.forEach((_,i)=>p.paste(row(i,i===1?state:'normal'),10,29+i*22));save('menu-'+state,p);return p});project('menu-proof',composites,['menu-normal','menu-hover','menu-pressed']);
const soundStates:Pixels[]=[],soundNames:string[]=[];
for(const on of [true,false])for(const state of states){const p=skin(112,36);if(state==='hover'||state==='pressed'){p.rect(8,8,96,20,state==='pressed'?63:65);p.line(10,29,101,29,48)}const icon=objs.get(`sound-${on?'on':'off'}-24`)!;p.paste(icon,8,6);text(p,on?'Sound on':'Sound off',37,11,'regular',state==='disabled'?51:state==='hover'?62:state==='pressed'?58:60);if(state==='disabled')for(let i=0;i<p.data.length;i++)if(p.data[i]===61||p.data[i]===62)p.data[i]=41;const n=`sound-${on?'on':'off'}-${state}`;save(n,p);soundNames.push(n);soundStates.push(p)}project('sound-buttons',soundStates,soundNames);
// Native cursor contract remains <=16; the 24/32 symbols serve web/UI displays.
const cursor=objs.get('hourglass-16')!;save('wait-cursor',cursor);project('wait-cursor',[cursor],['wait-cursor']);
const original=loadIndexed('../221b-r30/review/room-cast-native.png'.replace('..','art/studies'),JSON.parse(readFileSync('art/palette.json','utf8')));for(let i=0;i<original.data.length;i++)if(original.data[i]===63)original.data[i]=67;
const scene=clone(original);scene.paste(composites[1]!,38,11);enlarged(h+'review/menu.png',scene,pal,3);
const board=new Pixels(320,160,4);text(board,'Victorian controls',12,7,'bold');let x=14;for(const name of ['object-look-32','object-menu-32']){board.paste(loadIndexed('art/studies/interface-r28/export/'+name+'.png',pal),x,30);x+=51}board.paste(objs.get('hourglass-32')!,116,30);board.paste(objs.get('sound-on-32')!,167,30);board.paste(objs.get('sound-off-32')!,218,30);['Look','Menu','Wait','On','Off'].forEach((label,i)=>text(board,label,14+i*51,68));board.paste(soundStates[0]!,12,90);board.paste(soundStates[5]!,155,90);text(board,'Normal',12,134);text(board,'Hover / muted',155,134);enlarged(h+'review/controls.png',board,pal,3);
indexedGif(h+'review/menu-states.gif',composites.map(p=>{const q=clone(original);q.paste(p,38,11);return q}),pal,2,80);
writeFileSync(h+'native-jobs.json',JSON.stringify(jobs,null,2)+'\n');writeFileSync(h+'art.json',JSON.stringify({version:1,maxColours:68,palette:'palette.json',pictures:[],views:[{number:265,loops:[{cels:[{png:'export/wait-cursor.png',anchor:[8,8]}]}]}]},null,2)+'\n');
writeFileSync(h+'guides/handoff.json',JSON.stringify({status:'Art and interaction review; no game/web integration',palette:'r28 additive 68-colour palette, no production palette mutation',sourceBounds:bounds,wait:{view:265,canvas:[16,16],anchor:[8,8],png:'export/wait-cursor.png',largeSizes:[24,32],animation:'Static in this pass; do not rotate a square canvas around a different hotspot.'},sound:{size:[112,36],states,values:['on','off'],webOnly:true,aria:'Use a real button labelled Sound, aria-pressed=true when audio is enabled; icon and label both communicate state. Wire to the existing audio toggle.'},menu:{size:[244,178],at:[38,11],rowSize:[224,22],rowOrigin:[10,29],rowStep:22,bulletSize:[12,12],bulletOffset:[5,5],textOrigin:[25,4],font:'r29 New Century Schoolbook 12px regular in every item state; original metrics',textColours:{normal:pal[60],hover:pal[62],pressed:pal[58],disabled:pal[51]},labels,states,interaction:['Keep item text regular in every state; hover/focus use lighter purple and cream shades, never a weight change.','Pressed row uses inset shadow; moving focus never activates an item.','Escape/Carry on closes; Arrow keys move focus; Enter/Space activate.','Restore is disabled when no save exists.','Start again should retain the existing confirmation flow.','Use live text/state values, not baked screenshot labels.','Do not reuse the dialogue frame to size this menu.']},fontLicense:'../typography-r29/source/upstream/COPYING',nativeProjects:jobs.length},null,2)+'\n');console.log({objects:objs.size,menu:[244,178],states:4,soundStates:8,nativeProjects:jobs.length});
