/** Facial overlays are native cels over one immutable portrait; no per-frame generation. */
import assert from'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{Pixels}from'../../source/pixels.ts';import{loadIndexed,enlarged,indexedGif}from'../../source/study-tools.ts';import{pixeloramaProject}from'../../source/pixelorama-project.ts';
const h='art/studies/portraits-r18/',pal=JSON.parse(readFileSync(h+'palette.json','utf8')),specs=[{name:'watson',view:210,mouth:[37,31,8,4],eyes:[[31,18,8,4],[40,18,5,4]],lip:[39,31,5]},{name:'hudson',view:211,mouth:[34,29,10,5],eyes:[[31,19,7,5],[40,19,5,4]],lip:[36,29,6]},{name:'toby',view:212,mouth:[33,30,9,5],eyes:[[30,21,7,4],[39,20,5,4]],lip:[35,30,6]}],views:any[]=[],lineup=new Pixels(184,76,18),reports=[];
const crop=(p:Pixels,r:number[])=>{const q=new Pixels(56,64);for(let y=r[1]!;y<r[1]!+r[3]!;y++)for(let x=r[0]!;x<r[0]!+r[2]!;x++)q.dot(x,y,p.data[y*56+x]!);return q};
for(const[s,n]of specs.map((s,n)=>[s,n]as const)){const base=loadIndexed(h+`source/${s.name}-master.png`,pal),mouths:Pixels[]=[],eyes:Pixels[]=[];
 for(let f=0;f<3;f++){const m=crop(base,s.mouth);if(f){const[x,y,w]=s.lip as[number,number,number];m.line(x,y,x+w-1,y,9);m.line(x+1,y+1,x+w-2,y+1,2);if(f===2){m.line(x+2,y+2,x+w-2,y+2,2);m.dot(x+2,y+1,58)}m.line(x+2,y+(f===1?2:3),x+w-3,y+(f===1?2:3),45)}mouths.push(m);
 const e=new Pixels(56,64);for(const r of s.eyes){e.paste(crop(base,r),0,0);if(f){const[x,y,w,height]=r as[number,number,number,number];for(let xx=x;xx<x+w;xx++){const skin=base.data[(y+height)*56+xx]!;e.rect(xx,y,1,f===1?2:height,skin)}const yy=y+(f===1?1:2);e.line(x+1,yy,x+w-2,yy,29);if(f===2)e.dot(x+w-1,yy-1,29)}}eyes.push(e);}
 for(const p of [...mouths,...eyes])for(let i=0;i<p.data.length;i++)if(base.data[i]!<0)p.data[i]=-1;
 const loops=[[base],mouths,eyes];loops.forEach((fs,l)=>fs.forEach((p,c)=>writeFileSync(h+`export/${s.name}-${l}-${c}.png`,p.png(pal))));views.push({number:s.view,loops:loops.map(fs=>({cels:fs.map((_,c)=>({png:`export/${s.name}-${loops.indexOf(fs)}-${c}.png`,anchor:[0,0]}))}))});
 const combinations=[[0,0],[1,0],[2,0],[0,1],[0,2],[1,1],[2,2]],native=combinations.map(([m,e])=>[base,mouths[m!]!,eyes[e!]!]);writeFileSync(h+`source/${s.name}.pxo`,pixeloramaProject(pal,['Fixed bust','Mouth overlay','Eye overlay'],native,[{name:'mouth',from:1,to:3},{name:'blink',from:4,to:5}],{layers:[{locked:true,linkAll:true},{},{}],fps:8,userData:'56x64 [0,0]. Bust loop0; mouths loop1 closed/part/open; eyes loop2 open/half/closed. Exact fixed bust linked across every cel.'}));
 native.forEach((layers,i)=>{const out=new Pixels(56,64);layers.forEach(p=>out.paste(p,0,0));writeFileSync(h+`review/${s.name}-native-${i+1}.png`,out.png(pal));});
 const frames=[];for(let i=0;i<32;i++){const p=new Pixels(56,64,18),m=[0,1,2,1,0,2,1,0][i%8]!,e=i===22||i===24?1:i===23?2:0;p.paste(base,0,0);p.paste(mouths[m]!,0,0);p.paste(eyes[e]!,0,0);frames.push(p)}indexedGif(h+`review/${s.name}.gif`,frames,pal,5,13);
 const closed=new Pixels(56,64);closed.paste(base,0,0);closed.paste(mouths[0]!,0,0);closed.paste(eyes[0]!,0,0);assert.deepEqual(base.data,closed.data);for(const p of [...mouths,...eyes])for(let i=0;i<p.data.length;i++)if(p.data[i]!>=0)assert.ok(base.data[i]!>=0,'Overlay must remain inside the bust');
 lineup.paste(base,n*62,0);lineup.text(s.name.toUpperCase(),n*62+3,68,62);reports.push({name:s.name,closedMatchesMaster:true,overlaysStayWithinBust:true,canvas:[56,64],mouthRect:s.mouth,eyeRects:s.eyes});
}
enlarged(h+'review/cast.png',lineup,pal,4);writeFileSync(h+'art.json',JSON.stringify({version:1,maxColours:64,palette:'palette.json',pictures:[],views},null,2)+'\n');writeFileSync(h+'guides/landmarks.json',JSON.stringify(reports,null,2)+'\n');console.log(reports);

const keys=new Pixels(280,192,18);specs.forEach((s,j)=>{for(let i=0;i<5;i++)keys.paste(loadIndexed(h+'review/'+s.name+'-native-'+(i+1)+'.png',pal),i*56,j*64)});enlarged(h+'review/facial-keys.png',keys,pal,3);
writeFileSync(h+'native-jobs.json',JSON.stringify(specs.map(s=>({name:s.name,expected:Array.from({length:7},(_,i)=>'review/'+s.name+'-native-'+(i+1)+'.png')})),null,2)+'\n');
const castFrames:Pixels[]=[];for(let i=0;i<32;i++){const p=new Pixels(186,76,18);specs.forEach((s,k)=>{const m=[0,1,0,2,1,0,1,2][i%8]!,phase=(i+k*7)%32,e=phase===22||phase===24?1:phase===23?2:0;p.paste(loadIndexed(h+`export/${s.name}-0-0.png`,pal),k*62,0);p.paste(loadIndexed(h+`export/${s.name}-1-${m}.png`,pal),k*62,0);p.paste(loadIndexed(h+`export/${s.name}-2-${e}.png`,pal),k*62,0);p.text(s.name.toUpperCase(),k*62+3,68,62)});castFrames.push(p)}indexedGif(h+'review/cast.gif',castFrames,pal,4,13);
const dialogue=loadIndexed('art/studies/baker-street-r13/export/background.png',pal);dialogue.rect(5,124,310,71,2);dialogue.rect(6,125,308,69,48);dialogue.rect(7,126,306,67,62);dialogue.paste(loadIndexed(h+'export/watson-0-0.png',pal),10,128);dialogue.text('WATSON',76,132,2);dialogue.text('The clock has stopped at 3:17.',76,147,2);dialogue.text('Let us look more closely',76,161,2);dialogue.text('at the mechanism.',76,175,2);enlarged(h+'review/dialogue-layout.png',dialogue,pal,3);
